name: Deploy react-pc-app1

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: xgbbing/common-workflows/.github/workflows/common-deploy.yml@main
    with:
      app: react-pc-app1
    secrets: inherit